import * as core from '@actions/core';

// Helper function to construct body of PR review
// This one is used when tests are not run
export const buildNewFileReviewBody = (filePath, mcpSummary = '', rawOutput = '') => {
    const truncatedRaw = rawOutput.length > 30000 ? rawOutput.substring(0, 30000) + '\n\n... (truncated)' : rawOutput;

    return `### 🤖 AI-Generated Playwright Test

A test file has been committed to this PR: **\`${filePath}\`**

**To keep it:** Dismiss this review — the file stays on the branch.
**To remove it:** Delete the file or revert the commit.

> Tests were not executed. Set \`run-tests: true\` in the workflow to validate before merging.
${rawOutput ? `
<details>
<summary>Raw LLM Output</summary>

\`\`\`
${truncatedRaw}
\`\`\`

</details>
` : ''}${mcpSummary ? `\n${mcpSummary}\n` : ''}
---
*Generated by AI Playwright Test Generator*`;
};

// Helper function to construct body of PR review with test results
export const buildResultsReviewBody = ({ filePath, passed, exitCode, output, mcpSummary = '', rawOutput = '', testCode = '' }) => {
    // Use the test results to determine the status emoji and message
    const status = passed ? '✅ Tests Passed' : '❌ Tests Failed';

    // Truncate outputs if too long
    const truncatedOutput = output.length > 30000 ? output.substring(0, 30000) + '\n\n... (truncated)' : output;
    const truncatedRaw = rawOutput.length > 30000 ? rawOutput.substring(0, 30000) + '\n\n... (truncated)' : rawOutput;

    // Return formatted review body with test results and output
    return `### 🤖 AI-Generated Playwright Tests — ${status}

**Exit code:** ${exitCode}
**Suggested file:** \`${filePath}\`

<details>
<summary>Generated Test Code</summary>

\`\`\`typescript
${testCode}
\`\`\`

</details>

<details>
<summary>Test Output</summary>

\`\`\`
${truncatedOutput}
\`\`\`

</details>
${rawOutput ? `
<details>
<summary>Raw LLM Output</summary>

\`\`\`
${truncatedRaw}
\`\`\`

</details>
` : ''}${mcpSummary ? `\n${mcpSummary}\n` : ''}
---
*Generated and executed by AI Playwright Test Generator*`;
};

// This will be removed in future (just used for debugging currently)
export const logDiffInfo = (cleanDiff, rawDiff) => {
    core.info('=== FILTERED DIFF ===');
    core.info(cleanDiff);
    core.info('=== END FILTERED DIFF ===');
    core.info(`Filtered diff length: ${cleanDiff.length} characters`);
    core.info(`Original diff length: ${rawDiff.length} characters`);
};
