import * as core from '@actions/core';

// Helper function to construct body of PR review
// This one is used when tests are not run
export const buildNewFileReviewBody = (filePath, mcpSummary = '') => {
    return `### 🤖 AI-Generated Playwright Test

A new test file has been added to this PR: **\`${filePath}\`**

**Next steps:**
- Review the generated tests in the Files Changed tab
- Edit directly on the branch if adjustments are needed
- Revert the commit if the tests are not useful

> Tests were not executed. Set \`run-tests: true\` in the workflow to validate before committing.
${mcpSummary ? `\n${mcpSummary}\n` : ''}
---
*Generated by AI Playwright Test Generator*`;
};

// Helper function to construct body of PR review with test results
export const buildResultsReviewBody = ({ filePath, passed, exitCode, output, mcpSummary = '' }) => {
    // Use the test results to determine the status emoji and message
    const status = passed ? '✅ Tests Passed' : '❌ Tests Failed';

    // Truncate output if too long
    const truncatedOutput = output.length > 30000 ? output.substring(0, 30000) + '\n\n... (truncated)' : output;

    // Return formatted review body with test results and output
    return `### 🤖 AI-Generated Playwright Tests — ${status}

**Exit code:** ${exitCode}
**Test file:** \`${filePath}\`

<details>
<summary>Test Output</summary>

\`\`\`
${truncatedOutput}
\`\`\`

</details>
${mcpSummary ? `\n${mcpSummary}\n` : ''}
---
*Generated and executed by AI Playwright Test Generator*`;
};

// This will be removed in future (just used for debugging currently)
export const logDiffInfo = (cleanDiff, rawDiff) => {
    core.info('=== FILTERED DIFF ===');
    core.info(cleanDiff);
    core.info('=== END FILTERED DIFF ===');
    core.info(`Filtered diff length: ${cleanDiff.length} characters`);
    core.info(`Original diff length: ${rawDiff.length} characters`);
};
